// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Liveness probe for the IPC bridge: answers `"pong"`. It is the sample
	 *  command P0-04 uses to prove the round-trip Rust → generated bindings → UI,
	 *  and it stays afterwards as the cheapest check that the bridge is alive.
	 */
	ping: () => __TAURI_INVOKE<string>("ping"),
	/**  Opens the repository that contains `path` (a directory in it, or its root) and returns its first status. One repository is open at a time: once this succeeds, the one open before is closed and its id stops working, while opening the repository that is already open keeps its id. Every repository opened is recorded as the most recent one. Changes to it on disk are reported with the `repo-changed` event from now on. */
	openRepo: (path: string) => typedError<OpenedRepo, CommandError>(__TAURI_INVOKE("open_repo", { path })),
	/**  The current status of the open repository `repo_id`. A newer call for the same repository cancels this one, which then fails with the `cancelled` kind. */
	getStatus: (repoId: RepoId) => typedError<Status, CommandError>(__TAURI_INVOKE("get_status", { repoId })),
	/**  The repositories opened most recently, newest first, at most 20. */
	listRecentRepos: () => typedError<string[], CommandError>(__TAURI_INVOKE("list_recent_repos")),
};

/** Events */
export const events = {
	repoChanged: makeEvent<RepoChanged>("repo-changed"),
	repoWatchFailed: makeEvent<RepoWatchFailed>("repo-watch-failed"),
};

/* Types */
/**  Commit counts between HEAD and its upstream. */
export type AheadBehind = {
	/**  Commits on HEAD that the upstream lacks. */
	ahead: number,
	/**  Commits on the upstream that HEAD lacks. */
	behind: number,
};

/**
 *  What part of the repository changed, one per row of the §5 table, named
 *  as the `repo-changed` IPC event names them (§4: `status`, `refs`,
 *  `index`, `head`). It serialises as [`ChangeKind::name`].
 */
export type ChangeKind = 
/**
 *  A working-tree file was saved, created, deleted or renamed: re-run
 *  status. Also set when the ignore rules change.
 */
"status" | 
/**  `.git/index`: staging changed outside the app. */
"index" | 
/**  `.git/HEAD`: a checkout, or a detach. */
"head" | 
/**
 *  `.git/refs/**`, `packed-refs`, `ORIG_HEAD`, `FETCH_HEAD`, `shallow`:
 *  a commit, a branch or tag created, moved or deleted, a fetch, a stash.
 */
"refs" | 
/**
 *  An operation marker: `MERGE_HEAD`, `CHERRY_PICK_HEAD`, `REVERT_HEAD`,
 *  `BISECT_*`, `rebase-merge/`, `rebase-apply/`, `sequencer/`. A merge,
 *  rebase, cherry-pick, revert or bisect started or ended outside the app.
 */
"state" | 
/**  `.git/logs/**`: the reflog grew, so the undo history changed. */
"reflog" | 
/**
 *  `.git/config`, `.git/info/exclude`, `.git/info/attributes` or a
 *  `.gitattributes` in the tree.
 */
"config";

/**  The error of every command. */
export type CommandError = {
	kind: ErrorKind,
	/**  What happened, in English, with its causes. */
	message: string,
	/**
	 *  A command the user can run to fix it, for errors the app must not
	 *  fix itself (it never edits the user's git config).
	 */
	fix: string | null,
};

/**  What went wrong, for the frontend to branch on. */
export type ErrorKind = 
/**
 *  No usable git: none in settings, on `PATH` or bundled, or the one in
 *  settings is unusable (SPEC §5 Git binary resolution).
 */
"git_not_found" | 
/**  The path is not in a git repository, or its `.git` file is broken. */
"not_a_repository" | 
/**
 *  The path is in a bare repository or inside a `.git` directory, which
 *  have no working tree to show.
 */
"no_work_tree" | 
/**
 *  git refuses to work in the repository because another user owns it;
 *  `fix` holds the `safe.directory` command the user may run.
 */
"dubious_ownership" | 
/**  No open repository has this id (it was never opened in this run). */
"unknown_repo" | 
/**
 *  A newer request for the same thing superseded this one (SPEC §4
 *  Low-resource operation, rule 4). Not an error to show.
 */
"cancelled" | 
/**  Anything else; `message` says what. */
"failed";

/**
 *  One letter of git's `XY` status code. On the wire it is the variant's
 *  snake_case name (`"type_changed"`), not git's letter.
 */
export type FileStatus = 
/**  `.` */
"unmodified" | 
/**  `M` */
"modified" | 
/**  `T`: changed between file, symlink and submodule. */
"type_changed" | 
/**  `A` */
"added" | 
/**  `D` */
"deleted" | 
/**  `R` */
"renamed" | 
/**  `C` */
"copied" | 
/**  `U`, only in the conflict code of an unmerged entry. */
"unmerged" | 
/**  An untracked path (`?` record). */
"untracked" | 
/**  An ignored path (`!` record). */
"ignored";

/**
 *  Where HEAD points.
 * 
 *  Branch names are converted to UTF-8 lossily; commit ids are hex. On the
 *  wire it is tagged by `kind`: `{ "kind": "branch", "name": .., "oid": .. }`.
 */
export type Head = 
/**  On a branch that has commits. */
{ kind: "branch"; name: string; oid: string } | 
/**
 *  On a branch with no commits yet: a new repository, or after
 *  `git switch --orphan`.
 */
{ kind: "unborn"; name: string } | 
/**  On a commit rather than a branch. */
{ kind: "detached"; oid: string };

/**  The answer to `open_repo`: the first status of the repository, whose `repo.id` addresses it from now on, and why it is not being watched, if it is not. */
export type OpenedRepo = {
	status: Status,
	watch_error: WatchFailure | null,
};

/**
 *  Something changed on disk in an open repository: one coalesced event per
 *  150 ms window (250 ms on Windows). `kinds` says what to refresh.
 */
export type RepoChanged = {
	repo_id: RepoId,
	kinds: ChangeKind[],
};

/**
 *  Names one repository handle for as long as the process runs: the `id` of
 *  SPEC §5 `RepoInfo`, and how the app's IPC commands and the
 *  `repo-changed` event address an open repository (ADR 0008).
 * 
 *  Every [`Repo`] gets a new id when it is created ([`Repo::new`],
 *  [`open_repo`]); its clones share it. Ids are never reused within a
 *  process and mean nothing in another one, so they must not be persisted:
 *  the path is what identifies a repository across launches. The same
 *  working tree opened twice gets two ids, so a caller that keeps one handle
 *  per repository (the app does) must look the path up before opening it
 *  again.
 * 
 *  On the wire it is a plain number.
 */
export type RepoId = number;

/**
 *  §5 `RepoInfo`: which repository handle this is, and the `# branch.*`
 *  headers.
 * 
 *  One §5 field is not here yet: `state` (merging, rebasing, ...), which
 *  porcelain v2 does not report and P2-11 reads from the markers in `.git`.
 */
export type RepoInfo = {
	/**  The [`Repo`] the status was read from ([`Repo::id`]). */
	id: RepoId,
	/**  The root of the working tree, as the [`Repo`] names it. */
	path: string,
	head: Head,
	/**  The upstream branch, such as `origin/main`, when one is configured. */
	upstream: string | null,
	/**
	 *  How far HEAD is ahead of and behind `upstream`. `None` without an
	 *  upstream, and when the upstream branch no longer exists.
	 */
	ahead_behind: AheadBehind | null,
};

/**  The file watcher of an open repository stopped, so changes made outside the app are no longer reported. The app shows the warning; the polling fallback of SPEC §5 rule 8 is not there yet. */
export type RepoWatchFailed = {
	repo_id: RepoId,
	error: WatchFailure,
};

/**  What one `git status` run reports. */
export type Status = {
	repo: RepoInfo,
	/**  In the order git printed them. */
	entries: StatusEntry[],
};

/**
 *  One path that is not clean (§5 `StatusEntry`).
 * 
 *  `path` and `old_path` are relative to the root of the working tree and
 *  `/`-separated, exactly as git prints them. On Unix they are git's bytes,
 *  which need not be UTF-8; on Windows git prints UTF-8, and any invalid
 *  sequence is replaced. An ignored directory keeps its trailing `/`. Across
 *  IPC both are lossy strings (see the module docs).
 * 
 *  `index_status` and `worktree_status` are the two letters of git's `XY`
 *  code:
 *  - ordinary, renamed and copied entries: the change from HEAD to the index
 *    (X) and from the index to the working tree (Y);
 *  - unmerged entries (`is_conflicted`): the conflict, ours then theirs:
 *    `UU` both modified, `AA` both added, `DD` both deleted, `AU`/`UA` added
 *    by us/them, `DU`/`UD` deleted by us/them;
 *  - untracked and ignored entries: `Untracked` or `Ignored` in both, like
 *    porcelain v1's `??` and `!!`.
 * 
 *  §5 also lists `changelist_id`; it arrives with changelists (P6-01).
 */
export type StatusEntry = {
	path: string,
	/**  Where a renamed or copied path came from. */
	old_path: string | null,
	index_status: FileStatus,
	worktree_status: FileStatus,
	/**
	 *  The path has unmerged index entries: a merge, rebase, cherry-pick,
	 *  revert or stash apply stopped on it.
	 */
	is_conflicted: boolean,
	/**  The path is a submodule. */
	is_submodule: boolean,
};

/**  Why a repository is not being watched: its watcher could not start or stopped. `fix` is a command for the user to run when there is one (raising Linux's inotify watch limit). */
export type WatchFailure = {
	message: string,
	is_watch_limit: boolean,
	fix: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

