// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Liveness probe for the IPC bridge: answers `"pong"`. It is the sample
	 *  command P0-04 uses to prove the round-trip Rust → generated bindings → UI,
	 *  and it stays afterwards as the cheapest check that the bridge is alive.
	 */
	ping: () => __TAURI_INVOKE<string>("ping"),
};

